/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Thu Jan 10 10:36:01 2019. */

#include "mcu.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const MpuMcuQuery MpuMcuQueryCommand_query_default = MpuMcuQuery_COMMIT_ID;


const pb_field_t McuCommitId_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, McuCommitId, commit, commit, 0),
    PB_LAST_FIELD
};

const pb_field_t McuMpuMessage_fields[2] = {
    PB_ONEOF_FIELD(val,   1, MESSAGE , ONEOF, STATIC  , FIRST, McuMpuMessage, commit_info, commit_info, &McuCommitId_fields),
    PB_LAST_FIELD
};

const pb_field_t MpuMcuQueryCommand_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, MpuMcuQueryCommand, query, query, &MpuMcuQueryCommand_query_default),
    PB_LAST_FIELD
};

const pb_field_t MpuMcuMessage_fields[2] = {
    PB_ONEOF_FIELD(val,   1, MESSAGE , ONEOF, STATIC  , FIRST, MpuMcuMessage, query, query, &MpuMcuQueryCommand_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(McuMpuMessage, val.commit_info) < 65536 && pb_membersize(MpuMcuMessage, val.query) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_McuCommitId_McuMpuMessage_MpuMcuQueryCommand_MpuMcuMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(McuMpuMessage, val.commit_info) < 256 && pb_membersize(MpuMcuMessage, val.query) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_McuCommitId_McuMpuMessage_MpuMcuQueryCommand_MpuMcuMessage)
#endif


/* @@protoc_insertion_point(eof) */
